version: "3.8"

services:
  step-ca:
    image: smallstep/step-ca:0.25.2
    container_name: step-ca
    restart: unless-stopped
    network_mode: "host"
    environment:
      - DOCKER_STEPCA_INIT_NAME="Acme Corp"
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,$(hostname -f)
      - DOCKER_STEPCA_INIT_PASSWORD=mysecretpassword
    volumes:
      - step-ca:/home/step
volumes:
  step-ca:
