version: "3.8"

services:
  step-ca:
    image: smallstep/step-ca:0.25.2
    container_name: step-ca
    restart: unless-stopped
    network_mode: "host"
    environment:
      - DOCKER_STEPCA_INIT_NAME="Root CA My Corp"
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,$(hostname -f)
      - DOCKER_STEPCA_INIT_PASSWORD_FILE=/password.txt
    volumes:
      - step-ca:/home/step
      - ${PWD}/password.txt:/password.txt
volumes:
  step-ca:
