- name: Install Smallstap CA
  hosts: smallstep
  vars:
    - smallstep_version: "0.25.2"
  pre_tasks:
    - name: Install smallstep deb
      become: true
      ansible.builtin.apt:
        deb: https://github.com/smallstep/certificates/releases/download/v{{ smallstep_version }}/step-ca_{{ smallstep_version }}_amd64.deb

    - name: Download smallstep cli deb
      ansible.builtin.get_url:
        url: "https://github.com/smallstep/cli/releases/download/v{{ smallstep_version }}/step-cli_{{ smallstep_version }}_amd64.deb"
        dest: "/tmp/step-cli_{{ smallstep_version }}_amd64.deb"

    - name: Install smallstep cli deb
      become: true
      ansible.builtin.apt:
        deb: "/tmp/step-cli_{{ smallstep_version }}_amd64.deb"
        state: present

    # - name: Даем возможность запустить сервер step-ca от обычного пользователя
    #   become: true
    #   ansible.builtin.shell: |
    #     setcap CAP_NET_BIND_SERVICE=+eip $(which step-ca)

    - name: Получение пути к step-ca
      ansible.builtin.command: "which step-ca"
      register: step_ca_path
      changed_when: "'changed' in step_ca_path.stdout"

    - name: Установка CAP_NET_BIND_SERVICE
      become: true
      community.general.capabilities:
        path: "{{ step_ca_path.stdout }}"
        capability: cap_net_bind_service+ep
        state: present

    - name: Создание системного пользователя step
      become: true
      ansible.builtin.user:
        name: step
        comment: "System user for step-ca"
        home: /etc/step-ca
        shell: /bin/false
        system: true

    - name: Установка владельца и группы для /etc/step-ca
      become: true
      ansible.builtin.file:
        path: /etc/step-ca
        owner: step
        group: step
        recurse: true

    - name: Create step-ca.service
      become: true
      ansible.builtin.template:
        src: "step-ca.service.j2"
        dest: /etc/systemd/system/step-ca.service
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0644'
      register: step_ca_service