- hosts: freeipa
  become: true
  vars:
    - key_size: 4096
    - key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
    - country_name: RU
    - email_address: admin@apatsev.org.ru
    - organization_name: APATSEV

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Create directory /etc/docker-compose
      ansible.builtin.file:
        path: /etc/docker-compose
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Create directory /etc/docker-compose/freeipa-certificate
      ansible.builtin.file:
        path: /etc/docker-compose/freeipa-certificate
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
  roles:
    - role: geerlingguy.docker
  post_tasks:

    - name: Add user ubuntu to docker group
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        groups: docker
        append: true

    - name: Reset ssh connection to allow user changes to affect ansible user
      ansible.builtin.meta:
        reset_connection

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: "docker-compose.yaml.j2"
        dest: /etc/docker-compose/docker-compose.yaml
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0644'
      register: docker_compose

    - name: Copy freeipa.service
      ansible.builtin.copy:
        src: freeipa.service
        dest: /etc/systemd/system/freeipa.service
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0644'
      register: freeipa_service

    - name: Restart service freeipa
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: freeipa
      when: docker_compose.changed or freeipa_service

