- name: Install Smallstap CA
  hosts: smallstep
  vars:
    - smallstep_version: "0.25.2"
  pre_tasks:
    - name: Install smallstep deb
      become: true
      ansible.builtin.apt:
        deb: https://github.com/smallstep/certificates/releases/download/v{{ smallstep_version }}/step-ca_{{ smallstep_version }}_amd64.deb

    - name: Install smallstep cli deb
      become: true
      ansible.builtin.apt:
        deb: wget https://github.com/smallstep/cli/releases/download/v{{ smallstep_version }}/step-cli_{{ smallstep_version }}_amd64.deb

    - name: Даем возможность запустить сервер step-ca от обычного пользователя
      become: true
      ansible.builtin.shell: |
        setcap CAP_NET_BIND_SERVICE=+eip $(which step-ca)

    - name: Создание системного пользователя step
      become: true
      ansible.builtin.user:
        name: step
        comment: "System user for step-ca"
        home: /etc/step-ca
        shell: /bin/false
        system: true

    - name: Установка владельца и группы для /etc/step-ca
      become: true
      ansible.builtin.file:
        path: /etc/step-ca
        owner: step
        group: step
        recurse: true
