- name: Install FreeIPA
  hosts: freeipa
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Create directory /etc/docker-compose
      ansible.builtin.file:
        path: /etc/docker-compose
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Create directory /etc/docker-compose/freeipa-certificate
      ansible.builtin.file:
        path: /etc/docker-compose/freeipa-certificate
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
  roles:
    - role: geerlingguy.docker
  post_tasks:

    - name: Add user ubuntu to docker group
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        groups: docker
        append: true

    - name: Reset ssh connection to allow user changes to affect ansible user
      ansible.builtin.meta:
        reset_connection

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: "docker-compose.yaml.j2"
        dest: /etc/docker-compose/docker-compose.yaml
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0644'
      register: docker_compose

    - name: Pull a Docker compose project
      community.docker.docker_compose_v2_pull:
        project_src: /etc/docker-compose

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: /etc/docker-compose
      register: docker_compose_output
      ignore_errors: true

    - name: Pause for 10 minutes to start services docker-compose
      ansible.builtin.pause:
        minutes: 10

    - name: copy ipa.csr from freeipa to local
      fetch:
        src: /etc/docker-compose/freeipa-data/ipa.csr
        dest: /tmp/ipa.csr
        flat: yes

    - name: copy ipa.csr from local to smallstep
      copy:
        src: /tmp/ipa.csr
        dest: /etc/step-ca/certs/ipa.csr
      delegate_to: smallstep

    - name: Generate an OpenSSL certificate signed with your Step-CA
      ansible.builtin.shell:
        cmd: sudo step-cli certificate sign --profile intermediate-ca ipa.csr root_ca.crt /etc/step-ca/secrets/root_ca_key | sudo tee -a ipa.crt
        chdir: /etc/step-ca/certs
      register: generate_ipa_crt
      delegate_to: smallstep

    - debug: msg="{{ generate_ipa_crt.stdout }}"
    - debug: msg="{{ generate_ipa_crt.stderr }}"

    - name: Change ipa.crt file permission
      file:
        path: /etc/step-ca/certs/ipa.crt
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: copy ipa.crt from smallstep to local
      fetch:
        src: /etc/step-ca/certs/ipa.crt
        dest: /tmp/ipa.crt
        flat: yes
      delegate_to: smallstep

#    - name: copy ipa.crt from local to freeipa
#      copy:
#        src: /tmp/ipa.crt
#        dest: /etc/step-ca/certs/ipa.crt
#
#    - name: Remove external-ca from /etc/hosts
#      lineinfile:
#        path: /etc/docker-compose/docker-compose.yaml
#        state: absent
#        regexp: 'external-ca'

#    - name: 'Add external-cert-file=/freeipa-certificate/freeipa.crt to docker-compose.yaml'
#      lineinfile:
#        path: '/etc/docker-compose/docker-compose.yaml'
#        line: '      - --external-cert-file=/freeipa-certificate/ipa.crt'
#        insertbefore: "unattended"
#
#    - name: 'Add external-cert-file=/ca/ca.crt to docker-compose.yaml'
#      lineinfile:
#        path: '/etc/docker-compose/docker-compose.yaml'
#        line: '      - --external-cert-file=/ca/ca.crt'
#        insertbefore: "unattended"
